### ISSUE TITLE
Unsolvable floors

### ISSUE THREAD

**Issue by PartiallyTyped** [Unity-Technologies/obstacle-tower-env#106] opened 2019-07-27 12:49 UTC
i encountered an unsolvable floor, the tower is 75 and the floor is 20. There is a box puzzle and key requirement. There is no tile to place the box nor a key.

**Comment by awjuliani** [comment] 2019-07-29 17:27
Hi @isotropic-panda,

I just checked Tower 75 Floor 20. It is indeed solvable. The goal area for the block is in the middle of the room. 

![Screen Shot 2019-07-29 at 10 27 17 AM](https://user-images.githubusercontent.com/9065325/62068727-7cc18900-b1eb-11e9-9a21-bbf56e7150a1.png)

**Comment by isotropic-panda** [comment] 2019-07-30 11:03
Hi @awjuliani ,

Thanks for checking it out. This is weird because I was running the floor manually and checked everywhere but there wasn't a goal area. This was run on ubuntu 19.04. It could have been a visual glitch.

**Comment by awjuliani** [comment] 2019-07-30 17:42
@isotropic-panda 

If you are able to reproduce it again, please let me know. If there is indeed some issue with this floor (and perhaps a rendering glitch on linux), that is something we would obviously want to fix.

**Comment by isotropic-panda** [comment] 2019-07-31 06:39
Okay I will let you know. Is it possible to launch specific towers and floors directly from the binary? In the mean time, feel free to close this.

**Comment by awjuliani** [comment] 2019-07-31 17:01
Hi @isotropic-panda 

Currently the only way to set this is by using the reset parameters via the python api: https://github.com/Unity-Technologies/obstacle-tower-env/blob/master/reset-parameters.md

**Closed** 2023-12-15 21:11 UTC
Labels: discussion
